apiVersion: apps/v1
kind: Deployment
metadata:
  name: verordnungen-import-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: verordnungen-import-service
  template:
    metadata:
      labels:
        app: verordnungen-import-service
    spec:
      containers:
        - name: verordnungen-import-service
          image: f73-g2.cloudogu.net/achilles/verordnungen-import-service
          ports:
            - name: http
              containerPort: 8081
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: corona-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: corona-secret
                  key: password
            - name: MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: corona-secret
                  key: database
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: corona-secret
                  key: host
            - name: DATA_SERVICE_IP
              value: 10.103.249.73
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: verordnungen-import-service
  namespace: default
  labels:
    app: verordnungen-import-service
spec:
  selector:
    app: verordnungen-import-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 8081