apiVersion: v1
kind: Service
metadata:
  name: verordnungen-import-service
  namespace: default
  labels:
    app: verordnungen-import-service
spec:
  selector:
    app: verordnungen-import-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080